// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Ttd.FrontendTest.Instances.Item.Item.Data
{
    /// <summary>CRUD operations for data elements in an instance</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DataPatchRequestBody_patches_patch_op
    {
        [EnumMember(Value = "add")]
        #pragma warning disable CS1591
        Add,
        #pragma warning restore CS1591
        [EnumMember(Value = "remove")]
        #pragma warning disable CS1591
        Remove,
        #pragma warning restore CS1591
        [EnumMember(Value = "replace")]
        #pragma warning disable CS1591
        Replace,
        #pragma warning restore CS1591
        [EnumMember(Value = "move")]
        #pragma warning disable CS1591
        Move,
        #pragma warning restore CS1591
        [EnumMember(Value = "copy")]
        #pragma warning disable CS1591
        Copy,
        #pragma warning restore CS1591
        [EnumMember(Value = "test")]
        #pragma warning disable CS1591
        Test,
        #pragma warning restore CS1591
    }
}
