// <auto-generated/>
#pragma warning disable CS0618
using Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Authentication.Api.V1.Exchange.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Authentication.Api.V1.Exchange
{
    /// <summary>
    /// Builds and executes requests for operations under \authentication\api\v1\exchange
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ExchangeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.authentication.api.v1.exchange.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Authentication.Api.V1.Exchange.Item.WithTokenProviderItemRequestBuilder"/></returns>
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Authentication.Api.V1.Exchange.Item.WithTokenProviderItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("tokenProvider", position);
                return new global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Authentication.Api.V1.Exchange.Item.WithTokenProviderItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Authentication.Api.V1.Exchange.ExchangeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExchangeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/authentication/api/v1/exchange", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Authentication.Api.V1.Exchange.ExchangeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExchangeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/authentication/api/v1/exchange", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
