using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Altinn.App.SourceGenerator
{
    [Generator]
    public class AppModelGenerator: ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
        }

        public void Execute(GeneratorExecutionContext context)
        {
            string source = @"// <auto-generated/>
using System;
using Altinn.App.Core.Interface;
using Microsoft.Extensions.Logging;

namespace Altinn.App.Generated.Model;

public class AppModel : IAppModel
{
    private readonly ILogger<AppModel> _logger;
    
    public AppModel(ILogger<AppModel> logger)
    {
        _logger = logger;
    }
    
    public object Create(string classRef)
    {
        _logger.LogInformation($""CreateNewAppModel {classRef}"");

        return Activator.CreateInstance(GetModelType(classRef));
    }

    public Type GetModelType(string classRef)
    {
        _logger.LogInformation($""GetAppModelType {classRef}"");

        return Type.GetType(classRef);
    }
}
";
            context.AddSource("AppModel.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }
}