// <auto-generated />
using System;
using Altinn.App.ProcessEngine.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Altinn.App.ProcessEngine.Data.Migrations
{
    [DbContext(typeof(ProcessEngineDbContext))]
    [Migration("20251215133221_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Altinn.App.ProcessEngine.Models.ProcessEngineJob", b =>
                {
                    b.Property<string>("Identifier")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Identifier");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("process_engine_jobs", (string)null);
                });

            modelBuilder.Entity("Altinn.App.ProcessEngine.Models.ProcessEngineTask", b =>
                {
                    b.Property<string>("Identifier")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("BackoffUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("command_data");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobIdentifier")
                        .IsRequired()
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ProcessingOrder")
                        .HasColumnType("integer");

                    b.Property<int>("RequeueCount")
                        .HasColumnType("integer");

                    b.Property<string>("RetryStrategy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Identifier");

                    b.HasIndex("BackoffUntil");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("JobIdentifier");

                    b.HasIndex("Status");

                    b.ToTable("process_engine_tasks", (string)null);
                });

            modelBuilder.Entity("Altinn.App.ProcessEngine.Models.ProcessEngineJob", b =>
                {
                    b.OwnsOne("Altinn.App.ProcessEngine.Models.InstanceInformation", "InstanceInformation", b1 =>
                        {
                            b1.Property<string>("ProcessEngineJobIdentifier")
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("App")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("instance_app")
                                .HasAnnotation("Relational:JsonPropertyName", "app");

                            b1.Property<Guid>("InstanceGuid")
                                .HasColumnType("uuid")
                                .HasColumnName("instance_guid")
                                .HasAnnotation("Relational:JsonPropertyName", "instanceGuid");

                            b1.Property<int>("InstanceOwnerPartyId")
                                .HasColumnType("integer")
                                .HasColumnName("instance_owner_party_id")
                                .HasAnnotation("Relational:JsonPropertyName", "instanceOwnerPartyId");

                            b1.Property<string>("Org")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("instance_org")
                                .HasAnnotation("Relational:JsonPropertyName", "org");

                            b1.HasKey("ProcessEngineJobIdentifier");

                            b1.ToTable("process_engine_jobs");

                            b1.WithOwner()
                                .HasForeignKey("ProcessEngineJobIdentifier");
                        });

                    b.OwnsOne("Altinn.App.ProcessEngine.Models.ProcessEngineActor", "Actor", b1 =>
                        {
                            b1.Property<string>("ProcessEngineJobIdentifier")
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Language")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("actor_language")
                                .HasAnnotation("Relational:JsonPropertyName", "language");

                            b1.Property<string>("UserIdOrOrgNumber")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("actor_user_id_or_org_number")
                                .HasAnnotation("Relational:JsonPropertyName", "userIdOrOrgNumber");

                            b1.HasKey("ProcessEngineJobIdentifier");

                            b1.ToTable("process_engine_jobs");

                            b1.WithOwner()
                                .HasForeignKey("ProcessEngineJobIdentifier");
                        });

                    b.Navigation("Actor")
                        .IsRequired();

                    b.Navigation("InstanceInformation")
                        .IsRequired();
                });

            modelBuilder.Entity("Altinn.App.ProcessEngine.Models.ProcessEngineTask", b =>
                {
                    b.HasOne("Altinn.App.ProcessEngine.Models.ProcessEngineJob", null)
                        .WithMany("Tasks")
                        .HasForeignKey("JobIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Altinn.App.ProcessEngine.Models.ProcessEngineActor", "Actor", b1 =>
                        {
                            b1.Property<string>("ProcessEngineTaskIdentifier")
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Language")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("actor_language")
                                .HasAnnotation("Relational:JsonPropertyName", "language");

                            b1.Property<string>("UserIdOrOrgNumber")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("actor_user_id_or_org_number")
                                .HasAnnotation("Relational:JsonPropertyName", "userIdOrOrgNumber");

                            b1.HasKey("ProcessEngineTaskIdentifier");

                            b1.ToTable("process_engine_tasks");

                            b1.WithOwner()
                                .HasForeignKey("ProcessEngineTaskIdentifier");
                        });

                    b.Navigation("Actor")
                        .IsRequired();
                });

            modelBuilder.Entity("Altinn.App.ProcessEngine.Models.ProcessEngineJob", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
