// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ApplicationLogic : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The allowAnonymousOnStateless property</summary>
        public bool? AllowAnonymousOnStateless { get; set; }
        /// <summary>The allowInSubform property</summary>
        [Obsolete("")]
        public bool? AllowInSubform { get; set; }
        /// <summary>The autoCreate property</summary>
        public bool? AutoCreate { get; set; }
        /// <summary>The autoDeleteOnProcessEnd property</summary>
        public bool? AutoDeleteOnProcessEnd { get; set; }
        /// <summary>The classRef property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClassRef { get; set; }
#nullable restore
#else
        public string ClassRef { get; set; }
#endif
        /// <summary>The disallowUserCreate property</summary>
        public bool? DisallowUserCreate { get; set; }
        /// <summary>The disallowUserDelete property</summary>
        public bool? DisallowUserDelete { get; set; }
        /// <summary>The schemaRef property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SchemaRef { get; set; }
#nullable restore
#else
        public string SchemaRef { get; set; }
#endif
        /// <summary>The shadowFields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ShadowFields? ShadowFields { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ShadowFields ShadowFields { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ApplicationLogic"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ApplicationLogic CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ApplicationLogic();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowAnonymousOnStateless", n => { AllowAnonymousOnStateless = n.GetBoolValue(); } },
                { "allowInSubform", n => { AllowInSubform = n.GetBoolValue(); } },
                { "autoCreate", n => { AutoCreate = n.GetBoolValue(); } },
                { "autoDeleteOnProcessEnd", n => { AutoDeleteOnProcessEnd = n.GetBoolValue(); } },
                { "classRef", n => { ClassRef = n.GetStringValue(); } },
                { "disallowUserCreate", n => { DisallowUserCreate = n.GetBoolValue(); } },
                { "disallowUserDelete", n => { DisallowUserDelete = n.GetBoolValue(); } },
                { "schemaRef", n => { SchemaRef = n.GetStringValue(); } },
                { "shadowFields", n => { ShadowFields = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ShadowFields>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ShadowFields.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("allowAnonymousOnStateless", AllowAnonymousOnStateless);
            writer.WriteBoolValue("allowInSubform", AllowInSubform);
            writer.WriteBoolValue("autoCreate", AutoCreate);
            writer.WriteBoolValue("autoDeleteOnProcessEnd", AutoDeleteOnProcessEnd);
            writer.WriteStringValue("classRef", ClassRef);
            writer.WriteBoolValue("disallowUserCreate", DisallowUserCreate);
            writer.WriteBoolValue("disallowUserDelete", DisallowUserDelete);
            writer.WriteStringValue("schemaRef", SchemaRef);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ShadowFields>("shadowFields", ShadowFields);
        }
    }
}
#pragma warning restore CS0618
