// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ApplicationMetadata : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The altinnNugetVersion property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AltinnNugetVersion { get; set; }
#nullable restore
#else
        public string AltinnNugetVersion { get; set; }
#endif
        /// <summary>The autoDeleteOnProcessEnd property</summary>
        public bool? AutoDeleteOnProcessEnd { get; set; }
        /// <summary>The copyInstanceSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.CopyInstanceSettings? CopyInstanceSettings { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.CopyInstanceSettings CopyInstanceSettings { get; set; }
#endif
        /// <summary>The created property</summary>
        public DateTimeOffset? Created { get; set; }
        /// <summary>The createdBy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>The dataFields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.DataField>? DataFields { get; set; }
#nullable restore
#else
        public List<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.DataField> DataFields { get; set; }
#endif
        /// <summary>The dataTypes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.DataType>? DataTypes { get; set; }
#nullable restore
#else
        public List<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.DataType> DataTypes { get; set; }
#endif
        /// <summary>The disallowUserInstantiation property</summary>
        public bool? DisallowUserInstantiation { get; set; }
        /// <summary>The eFormidling property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.EFormidlingContract? EFormidling { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.EFormidlingContract EFormidling { get; set; }
#endif
        /// <summary>The externalApiIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ExternalApiIds { get; set; }
#nullable restore
#else
        public List<string> ExternalApiIds { get; set; }
#endif
        /// <summary>The features property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ApplicationMetadata_features? Features { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ApplicationMetadata_features Features { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The lastChanged property</summary>
        public DateTimeOffset? LastChanged { get; set; }
        /// <summary>The lastChangedBy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastChangedBy { get; set; }
#nullable restore
#else
        public string LastChangedBy { get; set; }
#endif
        /// <summary>The logo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Logo? Logo { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Logo Logo { get; set; }
#endif
        /// <summary>The messageBoxConfig property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MessageBoxConfig? MessageBoxConfig { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MessageBoxConfig MessageBoxConfig { get; set; }
#endif
        /// <summary>The onEntry property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.OnEntry? OnEntry { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.OnEntry OnEntry { get; set; }
#endif
        /// <summary>The org property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Org { get; set; }
#nullable restore
#else
        public string Org { get; set; }
#endif
        /// <summary>The partyTypesAllowed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PartyTypesAllowed? PartyTypesAllowed { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PartyTypesAllowed PartyTypesAllowed { get; set; }
#endif
        /// <summary>The presentationFields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.DataField>? PresentationFields { get; set; }
#nullable restore
#else
        public List<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.DataField> PresentationFields { get; set; }
#endif
        /// <summary>The processId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProcessId { get; set; }
#nullable restore
#else
        public string ProcessId { get; set; }
#endif
        /// <summary>The storageAccountNumber property</summary>
        public int? StorageAccountNumber { get; set; }
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ApplicationMetadata_title? Title { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ApplicationMetadata_title Title { get; set; }
#endif
        /// <summary>The validFrom property</summary>
        public DateTimeOffset? ValidFrom { get; set; }
        /// <summary>The validTo property</summary>
        public DateTimeOffset? ValidTo { get; set; }
        /// <summary>The versionId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VersionId { get; set; }
#nullable restore
#else
        public string VersionId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ApplicationMetadata"/> and sets the default values.
        /// </summary>
        public ApplicationMetadata()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ApplicationMetadata"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ApplicationMetadata CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ApplicationMetadata();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "altinnNugetVersion", n => { AltinnNugetVersion = n.GetStringValue(); } },
                { "autoDeleteOnProcessEnd", n => { AutoDeleteOnProcessEnd = n.GetBoolValue(); } },
                { "copyInstanceSettings", n => { CopyInstanceSettings = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.CopyInstanceSettings>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.CopyInstanceSettings.CreateFromDiscriminatorValue); } },
                { "created", n => { Created = n.GetDateTimeOffsetValue(); } },
                { "createdBy", n => { CreatedBy = n.GetStringValue(); } },
                { "dataFields", n => { DataFields = n.GetCollectionOfObjectValues<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.DataField>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.DataField.CreateFromDiscriminatorValue)?.AsList(); } },
                { "dataTypes", n => { DataTypes = n.GetCollectionOfObjectValues<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.DataType>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.DataType.CreateFromDiscriminatorValue)?.AsList(); } },
                { "disallowUserInstantiation", n => { DisallowUserInstantiation = n.GetBoolValue(); } },
                { "eFormidling", n => { EFormidling = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.EFormidlingContract>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.EFormidlingContract.CreateFromDiscriminatorValue); } },
                { "externalApiIds", n => { ExternalApiIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "features", n => { Features = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ApplicationMetadata_features>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ApplicationMetadata_features.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "lastChanged", n => { LastChanged = n.GetDateTimeOffsetValue(); } },
                { "lastChangedBy", n => { LastChangedBy = n.GetStringValue(); } },
                { "logo", n => { Logo = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Logo>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Logo.CreateFromDiscriminatorValue); } },
                { "messageBoxConfig", n => { MessageBoxConfig = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MessageBoxConfig>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MessageBoxConfig.CreateFromDiscriminatorValue); } },
                { "onEntry", n => { OnEntry = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.OnEntry>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.OnEntry.CreateFromDiscriminatorValue); } },
                { "org", n => { Org = n.GetStringValue(); } },
                { "partyTypesAllowed", n => { PartyTypesAllowed = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PartyTypesAllowed>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PartyTypesAllowed.CreateFromDiscriminatorValue); } },
                { "presentationFields", n => { PresentationFields = n.GetCollectionOfObjectValues<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.DataField>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.DataField.CreateFromDiscriminatorValue)?.AsList(); } },
                { "processId", n => { ProcessId = n.GetStringValue(); } },
                { "storageAccountNumber", n => { StorageAccountNumber = n.GetIntValue(); } },
                { "title", n => { Title = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ApplicationMetadata_title>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ApplicationMetadata_title.CreateFromDiscriminatorValue); } },
                { "validFrom", n => { ValidFrom = n.GetDateTimeOffsetValue(); } },
                { "validTo", n => { ValidTo = n.GetDateTimeOffsetValue(); } },
                { "versionId", n => { VersionId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("altinnNugetVersion", AltinnNugetVersion);
            writer.WriteBoolValue("autoDeleteOnProcessEnd", AutoDeleteOnProcessEnd);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.CopyInstanceSettings>("copyInstanceSettings", CopyInstanceSettings);
            writer.WriteDateTimeOffsetValue("created", Created);
            writer.WriteStringValue("createdBy", CreatedBy);
            writer.WriteCollectionOfObjectValues<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.DataField>("dataFields", DataFields);
            writer.WriteCollectionOfObjectValues<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.DataType>("dataTypes", DataTypes);
            writer.WriteBoolValue("disallowUserInstantiation", DisallowUserInstantiation);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.EFormidlingContract>("eFormidling", EFormidling);
            writer.WriteCollectionOfPrimitiveValues<string>("externalApiIds", ExternalApiIds);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ApplicationMetadata_features>("features", Features);
            writer.WriteStringValue("id", Id);
            writer.WriteDateTimeOffsetValue("lastChanged", LastChanged);
            writer.WriteStringValue("lastChangedBy", LastChangedBy);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Logo>("logo", Logo);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MessageBoxConfig>("messageBoxConfig", MessageBoxConfig);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.OnEntry>("onEntry", OnEntry);
            writer.WriteStringValue("org", Org);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PartyTypesAllowed>("partyTypesAllowed", PartyTypesAllowed);
            writer.WriteCollectionOfObjectValues<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.DataField>("presentationFields", PresentationFields);
            writer.WriteStringValue("processId", ProcessId);
            writer.WriteIntValue("storageAccountNumber", StorageAccountNumber);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ApplicationMetadata_title>("title", Title);
            writer.WriteDateTimeOffsetValue("validFrom", ValidFrom);
            writer.WriteDateTimeOffsetValue("validTo", ValidTo);
            writer.WriteStringValue("versionId", VersionId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
