// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Avgivergrp9787 : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The gruppeid property</summary>
        public double? Gruppeid { get; set; }
        /// <summary>The KontaktpersonEPostDatadef27688 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.KontaktpersonEPostdatadef27688? KontaktpersonEPostDatadef27688 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.KontaktpersonEPostdatadef27688 KontaktpersonEPostDatadef27688 { get; set; }
#endif
        /// <summary>The KontaktpersonTelefonnummerDatadef3 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.KontaktpersonTelefonnummerdatadef3? KontaktpersonTelefonnummerDatadef3 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.KontaktpersonTelefonnummerdatadef3 KontaktpersonTelefonnummerDatadef3 { get; set; }
#endif
        /// <summary>The OppgavegiverFodselsnummerDatadef26 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.OppgavegiverFodselsnummerdatadef26? OppgavegiverFodselsnummerDatadef26 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.OppgavegiverFodselsnummerdatadef26 OppgavegiverFodselsnummerDatadef26 { get; set; }
#endif
        /// <summary>The OppgavegiverNavnDatadef68 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.OppgavegiverNavndatadef68? OppgavegiverNavnDatadef68 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.OppgavegiverNavndatadef68 OppgavegiverNavnDatadef68 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Avgivergrp9787"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Avgivergrp9787 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Avgivergrp9787();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "gruppeid", n => { Gruppeid = n.GetDoubleValue(); } },
                { "KontaktpersonEPost-datadef-27688", n => { KontaktpersonEPostDatadef27688 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.KontaktpersonEPostdatadef27688>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.KontaktpersonEPostdatadef27688.CreateFromDiscriminatorValue); } },
                { "KontaktpersonTelefonnummer-datadef-3", n => { KontaktpersonTelefonnummerDatadef3 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.KontaktpersonTelefonnummerdatadef3>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.KontaktpersonTelefonnummerdatadef3.CreateFromDiscriminatorValue); } },
                { "OppgavegiverFodselsnummer-datadef-26", n => { OppgavegiverFodselsnummerDatadef26 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.OppgavegiverFodselsnummerdatadef26>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.OppgavegiverFodselsnummerdatadef26.CreateFromDiscriminatorValue); } },
                { "OppgavegiverNavn-datadef-68", n => { OppgavegiverNavnDatadef68 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.OppgavegiverNavndatadef68>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.OppgavegiverNavndatadef68.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("gruppeid", Gruppeid);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.KontaktpersonEPostdatadef27688>("KontaktpersonEPost-datadef-27688", KontaktpersonEPostDatadef27688);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.KontaktpersonTelefonnummerdatadef3>("KontaktpersonTelefonnummer-datadef-3", KontaktpersonTelefonnummerDatadef3);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.OppgavegiverFodselsnummerdatadef26>("OppgavegiverFodselsnummer-datadef-26", OppgavegiverFodselsnummerDatadef26);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.OppgavegiverNavndatadef68>("OppgavegiverNavn-datadef-68", OppgavegiverNavnDatadef68);
        }
    }
}
#pragma warning restore CS0618
