// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Begrunnelsegrp9317 : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The BegrunnelseForNyttNavnGrp9318 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.BegrunnelseForNyttNavngrp9318? BegrunnelseForNyttNavnGrp9318 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.BegrunnelseForNyttNavngrp9318 BegrunnelseForNyttNavnGrp9318 { get; set; }
#endif
        /// <summary>The gruppeid property</summary>
        public double? Gruppeid { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Begrunnelsegrp9317"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Begrunnelsegrp9317 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Begrunnelsegrp9317();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "BegrunnelseForNyttNavn-grp-9318", n => { BegrunnelseForNyttNavnGrp9318 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.BegrunnelseForNyttNavngrp9318>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.BegrunnelseForNyttNavngrp9318.CreateFromDiscriminatorValue); } },
                { "gruppeid", n => { Gruppeid = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.BegrunnelseForNyttNavngrp9318>("BegrunnelseForNyttNavn-grp-9318", BegrunnelseForNyttNavnGrp9318);
            writer.WriteDoubleValue("gruppeid", Gruppeid);
        }
    }
}
#pragma warning restore CS0618
