// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DataElement : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The blobStoragePath property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BlobStoragePath { get; set; }
#nullable restore
#else
        public string BlobStoragePath { get; set; }
#endif
        /// <summary>The contentHash property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContentHash { get; set; }
#nullable restore
#else
        public string ContentHash { get; set; }
#endif
        /// <summary>The contentType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContentType { get; set; }
#nullable restore
#else
        public string ContentType { get; set; }
#endif
        /// <summary>The created property</summary>
        public DateTimeOffset? Created { get; set; }
        /// <summary>The createdBy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>The dataType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DataType { get; set; }
#nullable restore
#else
        public string DataType { get; set; }
#endif
        /// <summary>The deleteStatus property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.DeleteStatus? DeleteStatus { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.DeleteStatus DeleteStatus { get; set; }
#endif
        /// <summary>The filename property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Filename { get; set; }
#nullable restore
#else
        public string Filename { get; set; }
#endif
        /// <summary>The fileScanResult property</summary>
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.FileScanResult? FileScanResult { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The instanceGuid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InstanceGuid { get; set; }
#nullable restore
#else
        public string InstanceGuid { get; set; }
#endif
        /// <summary>The isRead property</summary>
        public bool? IsRead { get; set; }
        /// <summary>The lastChanged property</summary>
        public DateTimeOffset? LastChanged { get; set; }
        /// <summary>The lastChangedBy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastChangedBy { get; set; }
#nullable restore
#else
        public string LastChangedBy { get; set; }
#endif
        /// <summary>The locked property</summary>
        public bool? Locked { get; set; }
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.KeyValueEntry>? Metadata { get; set; }
#nullable restore
#else
        public List<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.KeyValueEntry> Metadata { get; set; }
#endif
        /// <summary>The references property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Reference>? References { get; set; }
#nullable restore
#else
        public List<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Reference> References { get; set; }
#endif
        /// <summary>The refs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? Refs { get; set; }
#nullable restore
#else
        public List<Guid?> Refs { get; set; }
#endif
        /// <summary>The selfLinks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ResourceLinks? SelfLinks { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ResourceLinks SelfLinks { get; set; }
#endif
        /// <summary>The size property</summary>
        public long? Size { get; set; }
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>The userDefinedMetadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.KeyValueEntry>? UserDefinedMetadata { get; set; }
#nullable restore
#else
        public List<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.KeyValueEntry> UserDefinedMetadata { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.DataElement"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.DataElement CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.DataElement();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "blobStoragePath", n => { BlobStoragePath = n.GetStringValue(); } },
                { "contentHash", n => { ContentHash = n.GetStringValue(); } },
                { "contentType", n => { ContentType = n.GetStringValue(); } },
                { "created", n => { Created = n.GetDateTimeOffsetValue(); } },
                { "createdBy", n => { CreatedBy = n.GetStringValue(); } },
                { "dataType", n => { DataType = n.GetStringValue(); } },
                { "deleteStatus", n => { DeleteStatus = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.DeleteStatus>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.DeleteStatus.CreateFromDiscriminatorValue); } },
                { "fileScanResult", n => { FileScanResult = n.GetEnumValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.FileScanResult>(); } },
                { "filename", n => { Filename = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "instanceGuid", n => { InstanceGuid = n.GetStringValue(); } },
                { "isRead", n => { IsRead = n.GetBoolValue(); } },
                { "lastChanged", n => { LastChanged = n.GetDateTimeOffsetValue(); } },
                { "lastChangedBy", n => { LastChangedBy = n.GetStringValue(); } },
                { "locked", n => { Locked = n.GetBoolValue(); } },
                { "metadata", n => { Metadata = n.GetCollectionOfObjectValues<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.KeyValueEntry>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.KeyValueEntry.CreateFromDiscriminatorValue)?.AsList(); } },
                { "references", n => { References = n.GetCollectionOfObjectValues<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Reference>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Reference.CreateFromDiscriminatorValue)?.AsList(); } },
                { "refs", n => { Refs = n.GetCollectionOfPrimitiveValues<Guid?>()?.AsList(); } },
                { "selfLinks", n => { SelfLinks = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ResourceLinks>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ResourceLinks.CreateFromDiscriminatorValue); } },
                { "size", n => { Size = n.GetLongValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "userDefinedMetadata", n => { UserDefinedMetadata = n.GetCollectionOfObjectValues<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.KeyValueEntry>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.KeyValueEntry.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("blobStoragePath", BlobStoragePath);
            writer.WriteStringValue("contentHash", ContentHash);
            writer.WriteStringValue("contentType", ContentType);
            writer.WriteDateTimeOffsetValue("created", Created);
            writer.WriteStringValue("createdBy", CreatedBy);
            writer.WriteStringValue("dataType", DataType);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.DeleteStatus>("deleteStatus", DeleteStatus);
            writer.WriteStringValue("filename", Filename);
            writer.WriteEnumValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.FileScanResult>("fileScanResult", FileScanResult);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("instanceGuid", InstanceGuid);
            writer.WriteBoolValue("isRead", IsRead);
            writer.WriteDateTimeOffsetValue("lastChanged", LastChanged);
            writer.WriteStringValue("lastChangedBy", LastChangedBy);
            writer.WriteBoolValue("locked", Locked);
            writer.WriteCollectionOfObjectValues<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.KeyValueEntry>("metadata", Metadata);
            writer.WriteCollectionOfObjectValues<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Reference>("references", References);
            writer.WriteCollectionOfPrimitiveValues<Guid?>("refs", Refs);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ResourceLinks>("selfLinks", SelfLinks);
            writer.WriteLongValue("size", Size);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteCollectionOfObjectValues<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.KeyValueEntry>("userDefinedMetadata", UserDefinedMetadata);
        }
    }
}
#pragma warning restore CS0618
