// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Endringsmeldinggrp9786 : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The AvgiverGrp9787 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Avgivergrp9787? AvgiverGrp9787 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Avgivergrp9787 AvgiverGrp9787 { get; set; }
#endif
        /// <summary>The Gruppe2 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Gruppe2>? Gruppe2 { get; set; }
#nullable restore
#else
        public List<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Gruppe2> Gruppe2 { get; set; }
#endif
        /// <summary>The gruppeid property</summary>
        public double? Gruppeid { get; set; }
        /// <summary>The OversiktOverEndringeneGrp9788 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.OversiktOverEndringenegrp9788>? OversiktOverEndringeneGrp9788 { get; set; }
#nullable restore
#else
        public List<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.OversiktOverEndringenegrp9788> OversiktOverEndringeneGrp9788 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Endringsmeldinggrp9786"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Endringsmeldinggrp9786 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Endringsmeldinggrp9786();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "Avgiver-grp-9787", n => { AvgiverGrp9787 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Avgivergrp9787>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Avgivergrp9787.CreateFromDiscriminatorValue); } },
                { "Gruppe2", n => { Gruppe2 = n.GetCollectionOfObjectValues<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Gruppe2>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Gruppe2.CreateFromDiscriminatorValue)?.AsList(); } },
                { "gruppeid", n => { Gruppeid = n.GetDoubleValue(); } },
                { "OversiktOverEndringene-grp-9788", n => { OversiktOverEndringeneGrp9788 = n.GetCollectionOfObjectValues<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.OversiktOverEndringenegrp9788>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.OversiktOverEndringenegrp9788.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Avgivergrp9787>("Avgiver-grp-9787", AvgiverGrp9787);
            writer.WriteCollectionOfObjectValues<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Gruppe2>("Gruppe2", Gruppe2);
            writer.WriteDoubleValue("gruppeid", Gruppeid);
            writer.WriteCollectionOfObjectValues<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.OversiktOverEndringenegrp9788>("OversiktOverEndringene-grp-9788", OversiktOverEndringeneGrp9788);
        }
    }
}
#pragma warning restore CS0618
