// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum FileScanResult
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "NotApplicable")]
        #pragma warning disable CS1591
        NotApplicable,
        #pragma warning restore CS1591
        [EnumMember(Value = "Pending")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "Clean")]
        #pragma warning disable CS1591
        Clean,
        #pragma warning restore CS1591
        [EnumMember(Value = "Infected")]
        #pragma warning disable CS1591
        Infected,
        #pragma warning restore CS1591
    }
}
