// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Innledninggrp9309 : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The gruppeid property</summary>
        public double? Gruppeid { get; set; }
        /// <summary>The KontaktinformasjonGrp9311 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Kontaktinformasjongrp9311? KontaktinformasjonGrp9311 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Kontaktinformasjongrp9311 KontaktinformasjonGrp9311 { get; set; }
#endif
        /// <summary>The NavneendringenGjelderForGrp9310 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.NavneendringenGjelderForgrp9310? NavneendringenGjelderForGrp9310 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.NavneendringenGjelderForgrp9310 NavneendringenGjelderForGrp9310 { get; set; }
#endif
        /// <summary>The SamtykkeTilElektroniskKommunikasjonGrp9312 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.SamtykkeTilElektroniskKommunikasjongrp9312? SamtykkeTilElektroniskKommunikasjonGrp9312 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.SamtykkeTilElektroniskKommunikasjongrp9312 SamtykkeTilElektroniskKommunikasjonGrp9312 { get; set; }
#endif
        /// <summary>The SignererGrp9320 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Signerergrp9320? SignererGrp9320 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Signerergrp9320 SignererGrp9320 { get; set; }
#endif
        /// <summary>The TredjeSignererGrp9349 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.TredjeSignerergrp9349? TredjeSignererGrp9349 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.TredjeSignerergrp9349 TredjeSignererGrp9349 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Innledninggrp9309"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Innledninggrp9309 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Innledninggrp9309();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "gruppeid", n => { Gruppeid = n.GetDoubleValue(); } },
                { "Kontaktinformasjon-grp-9311", n => { KontaktinformasjonGrp9311 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Kontaktinformasjongrp9311>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Kontaktinformasjongrp9311.CreateFromDiscriminatorValue); } },
                { "NavneendringenGjelderFor-grp-9310", n => { NavneendringenGjelderForGrp9310 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.NavneendringenGjelderForgrp9310>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.NavneendringenGjelderForgrp9310.CreateFromDiscriminatorValue); } },
                { "SamtykkeTilElektroniskKommunikasjon-grp-9312", n => { SamtykkeTilElektroniskKommunikasjonGrp9312 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.SamtykkeTilElektroniskKommunikasjongrp9312>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.SamtykkeTilElektroniskKommunikasjongrp9312.CreateFromDiscriminatorValue); } },
                { "Signerer-grp-9320", n => { SignererGrp9320 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Signerergrp9320>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Signerergrp9320.CreateFromDiscriminatorValue); } },
                { "TredjeSignerer-grp-9349", n => { TredjeSignererGrp9349 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.TredjeSignerergrp9349>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.TredjeSignerergrp9349.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("gruppeid", Gruppeid);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Kontaktinformasjongrp9311>("Kontaktinformasjon-grp-9311", KontaktinformasjonGrp9311);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.NavneendringenGjelderForgrp9310>("NavneendringenGjelderFor-grp-9310", NavneendringenGjelderForGrp9310);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.SamtykkeTilElektroniskKommunikasjongrp9312>("SamtykkeTilElektroniskKommunikasjon-grp-9312", SamtykkeTilElektroniskKommunikasjonGrp9312);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Signerergrp9320>("Signerer-grp-9320", SignererGrp9320);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.TredjeSignerergrp9349>("TredjeSignerer-grp-9349", TredjeSignererGrp9349);
        }
    }
}
#pragma warning restore CS0618
