// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Kontaktinformasjongrp9311 : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The gruppeid property</summary>
        public double? Gruppeid { get; set; }
        /// <summary>The MelderArkivDatoDatadef34741 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderArkivDatodatadef34741? MelderArkivDatoDatadef34741 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderArkivDatodatadef34741 MelderArkivDatoDatadef34741 { get; set; }
#endif
        /// <summary>The MelderArkivTidspunktDatadef34742 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderArkivTidspunktdatadef34742? MelderArkivTidspunktDatadef34742 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderArkivTidspunktdatadef34742 MelderArkivTidspunktDatadef34742 { get; set; }
#endif
        /// <summary>The MelderEpostDatadef34739 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderEpostdatadef34739? MelderEpostDatadef34739 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderEpostdatadef34739 MelderEpostDatadef34739 { get; set; }
#endif
        /// <summary>The MelderEtternavnDatadef34735 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderEtternavndatadef34735? MelderEtternavnDatadef34735 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderEtternavndatadef34735 MelderEtternavnDatadef34735 { get; set; }
#endif
        /// <summary>The MelderFornavnDatadef34736 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderFornavndatadef34736? MelderFornavnDatadef34736 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderFornavndatadef34736 MelderFornavnDatadef34736 { get; set; }
#endif
        /// <summary>The MelderFultnavn property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderFultnavn? MelderFultnavn { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderFultnavn MelderFultnavn { get; set; }
#endif
        /// <summary>The MelderMalformDatadef34882 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderMalformdatadef34882? MelderMalformDatadef34882 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderMalformdatadef34882 MelderMalformDatadef34882 { get; set; }
#endif
        /// <summary>The MelderMellomnavnDatadef34737 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderMellomnavndatadef34737? MelderMellomnavnDatadef34737 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderMellomnavndatadef34737 MelderMellomnavnDatadef34737 { get; set; }
#endif
        /// <summary>The MelderMobiltelefonnummerDatadef34740 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderMobiltelefonnummerdatadef34740? MelderMobiltelefonnummerDatadef34740 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderMobiltelefonnummerdatadef34740 MelderMobiltelefonnummerDatadef34740 { get; set; }
#endif
        /// <summary>The MelderReferanseAltinnDatadef34743 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderReferanseAltinndatadef34743? MelderReferanseAltinnDatadef34743 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderReferanseAltinndatadef34743 MelderReferanseAltinnDatadef34743 { get; set; }
#endif
        /// <summary>The MeldingFodselsnummerDatadef34734 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MeldingFodselsnummerdatadef34734? MeldingFodselsnummerDatadef34734 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MeldingFodselsnummerdatadef34734 MeldingFodselsnummerDatadef34734 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Kontaktinformasjongrp9311"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Kontaktinformasjongrp9311 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Kontaktinformasjongrp9311();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "gruppeid", n => { Gruppeid = n.GetDoubleValue(); } },
                { "MelderArkivDato-datadef-34741", n => { MelderArkivDatoDatadef34741 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderArkivDatodatadef34741>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderArkivDatodatadef34741.CreateFromDiscriminatorValue); } },
                { "MelderArkivTidspunkt-datadef-34742", n => { MelderArkivTidspunktDatadef34742 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderArkivTidspunktdatadef34742>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderArkivTidspunktdatadef34742.CreateFromDiscriminatorValue); } },
                { "MelderEpost-datadef-34739", n => { MelderEpostDatadef34739 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderEpostdatadef34739>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderEpostdatadef34739.CreateFromDiscriminatorValue); } },
                { "MelderEtternavn-datadef-34735", n => { MelderEtternavnDatadef34735 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderEtternavndatadef34735>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderEtternavndatadef34735.CreateFromDiscriminatorValue); } },
                { "MelderFornavn-datadef-34736", n => { MelderFornavnDatadef34736 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderFornavndatadef34736>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderFornavndatadef34736.CreateFromDiscriminatorValue); } },
                { "MelderFultnavn", n => { MelderFultnavn = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderFultnavn>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderFultnavn.CreateFromDiscriminatorValue); } },
                { "MelderMalform-datadef-34882", n => { MelderMalformDatadef34882 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderMalformdatadef34882>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderMalformdatadef34882.CreateFromDiscriminatorValue); } },
                { "MelderMellomnavn-datadef-34737", n => { MelderMellomnavnDatadef34737 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderMellomnavndatadef34737>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderMellomnavndatadef34737.CreateFromDiscriminatorValue); } },
                { "MelderMobiltelefonnummer-datadef-34740", n => { MelderMobiltelefonnummerDatadef34740 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderMobiltelefonnummerdatadef34740>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderMobiltelefonnummerdatadef34740.CreateFromDiscriminatorValue); } },
                { "MelderReferanseAltinn-datadef-34743", n => { MelderReferanseAltinnDatadef34743 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderReferanseAltinndatadef34743>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderReferanseAltinndatadef34743.CreateFromDiscriminatorValue); } },
                { "MeldingFodselsnummer-datadef-34734", n => { MeldingFodselsnummerDatadef34734 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MeldingFodselsnummerdatadef34734>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MeldingFodselsnummerdatadef34734.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("gruppeid", Gruppeid);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderArkivDatodatadef34741>("MelderArkivDato-datadef-34741", MelderArkivDatoDatadef34741);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderArkivTidspunktdatadef34742>("MelderArkivTidspunkt-datadef-34742", MelderArkivTidspunktDatadef34742);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderEpostdatadef34739>("MelderEpost-datadef-34739", MelderEpostDatadef34739);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderEtternavndatadef34735>("MelderEtternavn-datadef-34735", MelderEtternavnDatadef34735);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderFornavndatadef34736>("MelderFornavn-datadef-34736", MelderFornavnDatadef34736);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderFultnavn>("MelderFultnavn", MelderFultnavn);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderMalformdatadef34882>("MelderMalform-datadef-34882", MelderMalformDatadef34882);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderMellomnavndatadef34737>("MelderMellomnavn-datadef-34737", MelderMellomnavnDatadef34737);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderMobiltelefonnummerdatadef34740>("MelderMobiltelefonnummer-datadef-34740", MelderMobiltelefonnummerDatadef34740);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MelderReferanseAltinndatadef34743>("MelderReferanseAltinn-datadef-34743", MelderReferanseAltinnDatadef34743);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MeldingFodselsnummerdatadef34734>("MeldingFodselsnummer-datadef-34734", MeldingFodselsnummerDatadef34734);
        }
    }
}
#pragma warning restore CS0618
