// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LinkedHidden : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The Value1 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value1 { get; set; }
#nullable restore
#else
        public string Value1 { get; set; }
#endif
        /// <summary>The Value10 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value10 { get; set; }
#nullable restore
#else
        public string Value10 { get; set; }
#endif
        /// <summary>The Value2 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value2 { get; set; }
#nullable restore
#else
        public string Value2 { get; set; }
#endif
        /// <summary>The Value3 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value3 { get; set; }
#nullable restore
#else
        public string Value3 { get; set; }
#endif
        /// <summary>The Value4 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value4 { get; set; }
#nullable restore
#else
        public string Value4 { get; set; }
#endif
        /// <summary>The Value5 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value5 { get; set; }
#nullable restore
#else
        public string Value5 { get; set; }
#endif
        /// <summary>The Value6 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value6 { get; set; }
#nullable restore
#else
        public string Value6 { get; set; }
#endif
        /// <summary>The Value7 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value7 { get; set; }
#nullable restore
#else
        public string Value7 { get; set; }
#endif
        /// <summary>The Value8 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value8 { get; set; }
#nullable restore
#else
        public string Value8 { get; set; }
#endif
        /// <summary>The Value9 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value9 { get; set; }
#nullable restore
#else
        public string Value9 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.LinkedHidden"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.LinkedHidden CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.LinkedHidden();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "Value1", n => { Value1 = n.GetStringValue(); } },
                { "Value10", n => { Value10 = n.GetStringValue(); } },
                { "Value2", n => { Value2 = n.GetStringValue(); } },
                { "Value3", n => { Value3 = n.GetStringValue(); } },
                { "Value4", n => { Value4 = n.GetStringValue(); } },
                { "Value5", n => { Value5 = n.GetStringValue(); } },
                { "Value6", n => { Value6 = n.GetStringValue(); } },
                { "Value7", n => { Value7 = n.GetStringValue(); } },
                { "Value8", n => { Value8 = n.GetStringValue(); } },
                { "Value9", n => { Value9 = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("Value1", Value1);
            writer.WriteStringValue("Value10", Value10);
            writer.WriteStringValue("Value2", Value2);
            writer.WriteStringValue("Value3", Value3);
            writer.WriteStringValue("Value4", Value4);
            writer.WriteStringValue("Value5", Value5);
            writer.WriteStringValue("Value6", Value6);
            writer.WriteStringValue("Value7", Value7);
            writer.WriteStringValue("Value8", Value8);
            writer.WriteStringValue("Value9", Value9);
        }
    }
}
#pragma warning restore CS0618
