// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MapData : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The Geometries property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Geometry>? Geometries { get; set; }
#nullable restore
#else
        public List<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Geometry> Geometries { get; set; }
#endif
        /// <summary>The Location property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Location { get; set; }
#nullable restore
#else
        public string Location { get; set; }
#endif
        /// <summary>The Selected property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Selected { get; set; }
#nullable restore
#else
        public string Selected { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MapData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MapData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MapData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "Geometries", n => { Geometries = n.GetCollectionOfObjectValues<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Geometry>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Geometry.CreateFromDiscriminatorValue)?.AsList(); } },
                { "Location", n => { Location = n.GetStringValue(); } },
                { "Selected", n => { Selected = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Geometry>("Geometries", Geometries);
            writer.WriteStringValue("Location", Location);
            writer.WriteStringValue("Selected", Selected);
        }
    }
}
#pragma warning restore CS0618
