// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NavneendringenGjelderForgrp9310 : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The gruppeid property</summary>
        public double? Gruppeid { get; set; }
        /// <summary>The MeldingMeldingsmottakerFodselsnummerDatadef33548 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MeldingMeldingsmottakerFodselsnummerdatadef33548? MeldingMeldingsmottakerFodselsnummerDatadef33548 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MeldingMeldingsmottakerFodselsnummerdatadef33548 MeldingMeldingsmottakerFodselsnummerDatadef33548 { get; set; }
#endif
        /// <summary>The SubjektEtternavnFolkeregistrertDatadef34729 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.SubjektEtternavnFolkeregistrertdatadef34729? SubjektEtternavnFolkeregistrertDatadef34729 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.SubjektEtternavnFolkeregistrertdatadef34729 SubjektEtternavnFolkeregistrertDatadef34729 { get; set; }
#endif
        /// <summary>The SubjektFodselsnummerDatadef34727 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.SubjektFodselsnummerdatadef34727? SubjektFodselsnummerDatadef34727 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.SubjektFodselsnummerdatadef34727 SubjektFodselsnummerDatadef34727 { get; set; }
#endif
        /// <summary>The SubjektFornavnFolkeregistrertDatadef34730 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.SubjektFornavnFolkeregistrertdatadef34730? SubjektFornavnFolkeregistrertDatadef34730 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.SubjektFornavnFolkeregistrertdatadef34730 SubjektFornavnFolkeregistrertDatadef34730 { get; set; }
#endif
        /// <summary>The SubjektMellomnavnFolkeregistrertDatadef34731 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.SubjektMellomnavnFolkeregistrertdatadef34731? SubjektMellomnavnFolkeregistrertDatadef34731 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.SubjektMellomnavnFolkeregistrertdatadef34731 SubjektMellomnavnFolkeregistrertDatadef34731 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.NavneendringenGjelderForgrp9310"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.NavneendringenGjelderForgrp9310 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.NavneendringenGjelderForgrp9310();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "gruppeid", n => { Gruppeid = n.GetDoubleValue(); } },
                { "MeldingMeldingsmottakerFodselsnummer-datadef-33548", n => { MeldingMeldingsmottakerFodselsnummerDatadef33548 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MeldingMeldingsmottakerFodselsnummerdatadef33548>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MeldingMeldingsmottakerFodselsnummerdatadef33548.CreateFromDiscriminatorValue); } },
                { "SubjektEtternavnFolkeregistrert-datadef-34729", n => { SubjektEtternavnFolkeregistrertDatadef34729 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.SubjektEtternavnFolkeregistrertdatadef34729>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.SubjektEtternavnFolkeregistrertdatadef34729.CreateFromDiscriminatorValue); } },
                { "SubjektFodselsnummer-datadef-34727", n => { SubjektFodselsnummerDatadef34727 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.SubjektFodselsnummerdatadef34727>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.SubjektFodselsnummerdatadef34727.CreateFromDiscriminatorValue); } },
                { "SubjektFornavnFolkeregistrert-datadef-34730", n => { SubjektFornavnFolkeregistrertDatadef34730 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.SubjektFornavnFolkeregistrertdatadef34730>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.SubjektFornavnFolkeregistrertdatadef34730.CreateFromDiscriminatorValue); } },
                { "SubjektMellomnavnFolkeregistrert-datadef-34731", n => { SubjektMellomnavnFolkeregistrertDatadef34731 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.SubjektMellomnavnFolkeregistrertdatadef34731>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.SubjektMellomnavnFolkeregistrertdatadef34731.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("gruppeid", Gruppeid);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MeldingMeldingsmottakerFodselsnummerdatadef33548>("MeldingMeldingsmottakerFodselsnummer-datadef-33548", MeldingMeldingsmottakerFodselsnummerDatadef33548);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.SubjektEtternavnFolkeregistrertdatadef34729>("SubjektEtternavnFolkeregistrert-datadef-34729", SubjektEtternavnFolkeregistrertDatadef34729);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.SubjektFodselsnummerdatadef34727>("SubjektFodselsnummer-datadef-34727", SubjektFodselsnummerDatadef34727);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.SubjektFornavnFolkeregistrertdatadef34730>("SubjektFornavnFolkeregistrert-datadef-34730", SubjektFornavnFolkeregistrertDatadef34730);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.SubjektMellomnavnFolkeregistrertdatadef34731>("SubjektMellomnavnFolkeregistrert-datadef-34731", SubjektMellomnavnFolkeregistrertDatadef34731);
        }
    }
}
#pragma warning restore CS0618
