// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NyttNavngrp9314 : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The gruppeid property</summary>
        public double? Gruppeid { get; set; }
        /// <summary>The PersonBekrefterNyttNavn property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonBekrefterNyttNavn? PersonBekrefterNyttNavn { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonBekrefterNyttNavn PersonBekrefterNyttNavn { get; set; }
#endif
        /// <summary>The PersonEtternavnNyttDatadef34757 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnNyttdatadef34757? PersonEtternavnNyttDatadef34757 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnNyttdatadef34757 PersonEtternavnNyttDatadef34757 { get; set; }
#endif
        /// <summary>The PersonFornavnNyttDatadef34758 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonFornavnNyttdatadef34758? PersonFornavnNyttDatadef34758 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonFornavnNyttdatadef34758 PersonFornavnNyttDatadef34758 { get; set; }
#endif
        /// <summary>The PersonMellomnavnNyttDatadef34759 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnNyttdatadef34759? PersonMellomnavnNyttDatadef34759 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnNyttdatadef34759 PersonMellomnavnNyttDatadef34759 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.NyttNavngrp9314"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.NyttNavngrp9314 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.NyttNavngrp9314();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "gruppeid", n => { Gruppeid = n.GetDoubleValue(); } },
                { "PersonBekrefterNyttNavn", n => { PersonBekrefterNyttNavn = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonBekrefterNyttNavn>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonBekrefterNyttNavn.CreateFromDiscriminatorValue); } },
                { "PersonEtternavnNytt-datadef-34757", n => { PersonEtternavnNyttDatadef34757 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnNyttdatadef34757>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnNyttdatadef34757.CreateFromDiscriminatorValue); } },
                { "PersonFornavnNytt-datadef-34758", n => { PersonFornavnNyttDatadef34758 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonFornavnNyttdatadef34758>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonFornavnNyttdatadef34758.CreateFromDiscriminatorValue); } },
                { "PersonMellomnavnNytt-datadef-34759", n => { PersonMellomnavnNyttDatadef34759 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnNyttdatadef34759>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnNyttdatadef34759.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("gruppeid", Gruppeid);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonBekrefterNyttNavn>("PersonBekrefterNyttNavn", PersonBekrefterNyttNavn);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnNyttdatadef34757>("PersonEtternavnNytt-datadef-34757", PersonEtternavnNyttDatadef34757);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonFornavnNyttdatadef34758>("PersonFornavnNytt-datadef-34758", PersonFornavnNyttDatadef34758);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnNyttdatadef34759>("PersonMellomnavnNytt-datadef-34759", PersonMellomnavnNyttDatadef34759);
        }
    }
}
#pragma warning restore CS0618
