// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PartyTypesAllowed : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The bankruptcyEstate property</summary>
        public bool? BankruptcyEstate { get; set; }
        /// <summary>The organisation property</summary>
        public bool? Organisation { get; set; }
        /// <summary>The person property</summary>
        public bool? Person { get; set; }
        /// <summary>The subUnit property</summary>
        public bool? SubUnit { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PartyTypesAllowed"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PartyTypesAllowed CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PartyTypesAllowed();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bankruptcyEstate", n => { BankruptcyEstate = n.GetBoolValue(); } },
                { "organisation", n => { Organisation = n.GetBoolValue(); } },
                { "person", n => { Person = n.GetBoolValue(); } },
                { "subUnit", n => { SubUnit = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("bankruptcyEstate", BankruptcyEstate);
            writer.WriteBoolValue("organisation", Organisation);
            writer.WriteBoolValue("person", Person);
            writer.WriteBoolValue("subUnit", SubUnit);
        }
    }
}
#pragma warning restore CS0618
