// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ReferenceType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "DataElement")]
        #pragma warning disable CS1591
        DataElement,
        #pragma warning restore CS1591
        [EnumMember(Value = "Task")]
        #pragma warning disable CS1591
        Task,
        #pragma warning restore CS1591
    }
}
