// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum RelationType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "GeneratedFrom")]
        #pragma warning disable CS1591
        GeneratedFrom,
        #pragma warning restore CS1591
    }
}
