// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SamtykkeTilElektroniskKommunikasjongrp9312 : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The AvgiverFolkeregisterSamtykkeDatadef34756 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.AvgiverFolkeregisterSamtykkedatadef34756? AvgiverFolkeregisterSamtykkeDatadef34756 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.AvgiverFolkeregisterSamtykkedatadef34756 AvgiverFolkeregisterSamtykkeDatadef34756 { get; set; }
#endif
        /// <summary>The AvgiverSkattSamtykkeDatadef34755 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.AvgiverSkattSamtykkedatadef34755? AvgiverSkattSamtykkeDatadef34755 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.AvgiverSkattSamtykkedatadef34755 AvgiverSkattSamtykkeDatadef34755 { get; set; }
#endif
        /// <summary>The gruppeid property</summary>
        public double? Gruppeid { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.SamtykkeTilElektroniskKommunikasjongrp9312"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.SamtykkeTilElektroniskKommunikasjongrp9312 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.SamtykkeTilElektroniskKommunikasjongrp9312();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AvgiverFolkeregisterSamtykke-datadef-34756", n => { AvgiverFolkeregisterSamtykkeDatadef34756 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.AvgiverFolkeregisterSamtykkedatadef34756>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.AvgiverFolkeregisterSamtykkedatadef34756.CreateFromDiscriminatorValue); } },
                { "AvgiverSkattSamtykke-datadef-34755", n => { AvgiverSkattSamtykkeDatadef34755 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.AvgiverSkattSamtykkedatadef34755>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.AvgiverSkattSamtykkedatadef34755.CreateFromDiscriminatorValue); } },
                { "gruppeid", n => { Gruppeid = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.AvgiverFolkeregisterSamtykkedatadef34756>("AvgiverFolkeregisterSamtykke-datadef-34756", AvgiverFolkeregisterSamtykkeDatadef34756);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.AvgiverSkattSamtykkedatadef34755>("AvgiverSkattSamtykke-datadef-34755", AvgiverSkattSamtykkeDatadef34755);
            writer.WriteDoubleValue("gruppeid", Gruppeid);
        }
    }
}
#pragma warning restore CS0618
