// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Skjema : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The Adresse property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Adresse? Adresse { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Adresse Adresse { get; set; }
#endif
        /// <summary>The BegrunnelseFrivillig property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BegrunnelseFrivillig { get; set; }
#nullable restore
#else
        public string BegrunnelseFrivillig { get; set; }
#endif
        /// <summary>The BegrunnelseGrp9317 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Begrunnelsegrp9317? BegrunnelseGrp9317 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Begrunnelsegrp9317 BegrunnelseGrp9317 { get; set; }
#endif
        /// <summary>The blankettnummer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Blankettnummer { get; set; }
#nullable restore
#else
        public string Blankettnummer { get; set; }
#endif
        /// <summary>The ChooseExtraPages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChooseExtraPages { get; set; }
#nullable restore
#else
        public string ChooseExtraPages { get; set; }
#endif
        /// <summary>The Colors property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Colors { get; set; }
#nullable restore
#else
        public string Colors { get; set; }
#endif
        /// <summary>The ColorsLabels property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ColorsLabels { get; set; }
#nullable restore
#else
        public List<string> ColorsLabels { get; set; }
#endif
        /// <summary>The ColorsLabelsVerify property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ColorsLabelsVerify { get; set; }
#nullable restore
#else
        public string ColorsLabelsVerify { get; set; }
#endif
        /// <summary>The ConflictingOptions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ConflictingOptions? ConflictingOptions { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ConflictingOptions ConflictingOptions { get; set; }
#endif
        /// <summary>The etatid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Etatid { get; set; }
#nullable restore
#else
        public string Etatid { get; set; }
#endif
        /// <summary>The FilteredOptions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.FilteredOptions? FilteredOptions { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.FilteredOptions FilteredOptions { get; set; }
#endif
        /// <summary>The Food property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Food { get; set; }
#nullable restore
#else
        public string Food { get; set; }
#endif
        /// <summary>The FoodLabel property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FoodLabel { get; set; }
#nullable restore
#else
        public string FoodLabel { get; set; }
#endif
        /// <summary>The GridData property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.GridData? GridData { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.GridData GridData { get; set; }
#endif
        /// <summary>The gruppeid property</summary>
        public double? Gruppeid { get; set; }
        /// <summary>The InnledningGrp9309 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Innledninggrp9309? InnledningGrp9309 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Innledninggrp9309 InnledningGrp9309 { get; set; }
#endif
        /// <summary>The LinkedHidden property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.LinkedHidden? LinkedHidden { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.LinkedHidden LinkedHidden { get; set; }
#endif
        /// <summary>The MapData property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MapData? MapData { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MapData MapData { get; set; }
#endif
        /// <summary>The neverValidatedInput property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NeverValidatedInput { get; set; }
#nullable restore
#else
        public string NeverValidatedInput { get; set; }
#endif
        /// <summary>The Numeric property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Numeric? Numeric { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Numeric Numeric { get; set; }
#endif
        /// <summary>The NyttNavnGrp9313 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.NyttNavngrp9313? NyttNavnGrp9313 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.NyttNavngrp9313 NyttNavnGrp9313 { get; set; }
#endif
        /// <summary>The Radioknapp property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Radioknapp { get; set; }
#nullable restore
#else
        public string Radioknapp { get; set; }
#endif
        /// <summary>The ShiftingOptions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ShiftingOptions? ShiftingOptions { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ShiftingOptions ShiftingOptions { get; set; }
#endif
        /// <summary>The skjemanummer property</summary>
        public double? Skjemanummer { get; set; }
        /// <summary>The spesifikasjonsnummer property</summary>
        public double? Spesifikasjonsnummer { get; set; }
        /// <summary>The TestCustomButtonInput property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TestCustomButtonInput { get; set; }
#nullable restore
#else
        public string TestCustomButtonInput { get; set; }
#endif
        /// <summary>The TestCustomButtonReadOnlyInput property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TestCustomButtonReadOnlyInput { get; set; }
#nullable restore
#else
        public string TestCustomButtonReadOnlyInput { get; set; }
#endif
        /// <summary>The TilknytningGrp9315 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Tilknytninggrp9315? TilknytningGrp9315 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Tilknytninggrp9315 TilknytningGrp9315 { get; set; }
#endif
        /// <summary>The tittel property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Tittel { get; set; }
#nullable restore
#else
        public string Tittel { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Skjema"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Skjema CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Skjema();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "Adresse", n => { Adresse = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Adresse>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Adresse.CreateFromDiscriminatorValue); } },
                { "BegrunnelseFrivillig", n => { BegrunnelseFrivillig = n.GetStringValue(); } },
                { "Begrunnelse-grp-9317", n => { BegrunnelseGrp9317 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Begrunnelsegrp9317>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Begrunnelsegrp9317.CreateFromDiscriminatorValue); } },
                { "blankettnummer", n => { Blankettnummer = n.GetStringValue(); } },
                { "ChooseExtraPages", n => { ChooseExtraPages = n.GetStringValue(); } },
                { "Colors", n => { Colors = n.GetStringValue(); } },
                { "ColorsLabels", n => { ColorsLabels = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "ColorsLabelsVerify", n => { ColorsLabelsVerify = n.GetStringValue(); } },
                { "ConflictingOptions", n => { ConflictingOptions = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ConflictingOptions>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ConflictingOptions.CreateFromDiscriminatorValue); } },
                { "etatid", n => { Etatid = n.GetStringValue(); } },
                { "FilteredOptions", n => { FilteredOptions = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.FilteredOptions>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.FilteredOptions.CreateFromDiscriminatorValue); } },
                { "Food", n => { Food = n.GetStringValue(); } },
                { "FoodLabel", n => { FoodLabel = n.GetStringValue(); } },
                { "GridData", n => { GridData = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.GridData>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.GridData.CreateFromDiscriminatorValue); } },
                { "gruppeid", n => { Gruppeid = n.GetDoubleValue(); } },
                { "Innledning-grp-9309", n => { InnledningGrp9309 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Innledninggrp9309>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Innledninggrp9309.CreateFromDiscriminatorValue); } },
                { "LinkedHidden", n => { LinkedHidden = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.LinkedHidden>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.LinkedHidden.CreateFromDiscriminatorValue); } },
                { "MapData", n => { MapData = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MapData>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MapData.CreateFromDiscriminatorValue); } },
                { "neverValidatedInput", n => { NeverValidatedInput = n.GetStringValue(); } },
                { "Numeric", n => { Numeric = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Numeric>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Numeric.CreateFromDiscriminatorValue); } },
                { "NyttNavn-grp-9313", n => { NyttNavnGrp9313 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.NyttNavngrp9313>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.NyttNavngrp9313.CreateFromDiscriminatorValue); } },
                { "Radioknapp", n => { Radioknapp = n.GetStringValue(); } },
                { "ShiftingOptions", n => { ShiftingOptions = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ShiftingOptions>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ShiftingOptions.CreateFromDiscriminatorValue); } },
                { "skjemanummer", n => { Skjemanummer = n.GetDoubleValue(); } },
                { "spesifikasjonsnummer", n => { Spesifikasjonsnummer = n.GetDoubleValue(); } },
                { "TestCustomButtonInput", n => { TestCustomButtonInput = n.GetStringValue(); } },
                { "TestCustomButtonReadOnlyInput", n => { TestCustomButtonReadOnlyInput = n.GetStringValue(); } },
                { "Tilknytning-grp-9315", n => { TilknytningGrp9315 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Tilknytninggrp9315>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Tilknytninggrp9315.CreateFromDiscriminatorValue); } },
                { "tittel", n => { Tittel = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Adresse>("Adresse", Adresse);
            writer.WriteStringValue("BegrunnelseFrivillig", BegrunnelseFrivillig);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Begrunnelsegrp9317>("Begrunnelse-grp-9317", BegrunnelseGrp9317);
            writer.WriteStringValue("blankettnummer", Blankettnummer);
            writer.WriteStringValue("ChooseExtraPages", ChooseExtraPages);
            writer.WriteStringValue("Colors", Colors);
            writer.WriteCollectionOfPrimitiveValues<string>("ColorsLabels", ColorsLabels);
            writer.WriteStringValue("ColorsLabelsVerify", ColorsLabelsVerify);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ConflictingOptions>("ConflictingOptions", ConflictingOptions);
            writer.WriteStringValue("etatid", Etatid);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.FilteredOptions>("FilteredOptions", FilteredOptions);
            writer.WriteStringValue("Food", Food);
            writer.WriteStringValue("FoodLabel", FoodLabel);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.GridData>("GridData", GridData);
            writer.WriteDoubleValue("gruppeid", Gruppeid);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Innledninggrp9309>("Innledning-grp-9309", InnledningGrp9309);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.LinkedHidden>("LinkedHidden", LinkedHidden);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.MapData>("MapData", MapData);
            writer.WriteStringValue("neverValidatedInput", NeverValidatedInput);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Numeric>("Numeric", Numeric);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.NyttNavngrp9313>("NyttNavn-grp-9313", NyttNavnGrp9313);
            writer.WriteStringValue("Radioknapp", Radioknapp);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ShiftingOptions>("ShiftingOptions", ShiftingOptions);
            writer.WriteDoubleValue("skjemanummer", Skjemanummer);
            writer.WriteDoubleValue("spesifikasjonsnummer", Spesifikasjonsnummer);
            writer.WriteStringValue("TestCustomButtonInput", TestCustomButtonInput);
            writer.WriteStringValue("TestCustomButtonReadOnlyInput", TestCustomButtonReadOnlyInput);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.Tilknytninggrp9315>("Tilknytning-grp-9315", TilknytningGrp9315);
            writer.WriteStringValue("tittel", Tittel);
        }
    }
}
#pragma warning restore CS0618
