// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TilknytningMellomnavn3grp9354 : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The gruppeid property</summary>
        public double? Gruppeid { get; set; }
        /// <summary>The PersonMellomnavnTredjeDatadef34936 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjedatadef34936? PersonMellomnavnTredjeDatadef34936 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjedatadef34936 PersonMellomnavnTredjeDatadef34936 { get; set; }
#endif
        /// <summary>The PersonMellomnavnTredjeTilknytningBeskrivelseDatadef34938 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknytningBeskrivelsedatadef34938? PersonMellomnavnTredjeTilknytningBeskrivelseDatadef34938 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknytningBeskrivelsedatadef34938 PersonMellomnavnTredjeTilknytningBeskrivelseDatadef34938 { get; set; }
#endif
        /// <summary>The PersonMellomnavnTredjeTilknytningstypeDatadef34937 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknytningstypedatadef34937? PersonMellomnavnTredjeTilknytningstypeDatadef34937 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknytningstypedatadef34937 PersonMellomnavnTredjeTilknytningstypeDatadef34937 { get; set; }
#endif
        /// <summary>The PersonMellomnavnTredjeTilknyttetGardBruksnummerDatadef34944 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetGardBruksnummerdatadef34944? PersonMellomnavnTredjeTilknyttetGardBruksnummerDatadef34944 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetGardBruksnummerdatadef34944 PersonMellomnavnTredjeTilknyttetGardBruksnummerDatadef34944 { get; set; }
#endif
        /// <summary>The PersonMellomnavnTredjeTilknyttetGardFestenummerDatadef34945 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetGardFestenummerdatadef34945? PersonMellomnavnTredjeTilknyttetGardFestenummerDatadef34945 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetGardFestenummerdatadef34945 PersonMellomnavnTredjeTilknyttetGardFestenummerDatadef34945 { get; set; }
#endif
        /// <summary>The PersonMellomnavnTredjeTilknyttetGardGardsnummerDatadef34943 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetGardGardsnummerdatadef34943? PersonMellomnavnTredjeTilknyttetGardGardsnummerDatadef34943 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetGardGardsnummerdatadef34943 PersonMellomnavnTredjeTilknyttetGardGardsnummerDatadef34943 { get; set; }
#endif
        /// <summary>The PersonMellomnavnTredjeTilknyttetGardKommunenummerDatadef34942 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetGardKommunenummerdatadef34942? PersonMellomnavnTredjeTilknyttetGardKommunenummerDatadef34942 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetGardKommunenummerdatadef34942 PersonMellomnavnTredjeTilknyttetGardKommunenummerDatadef34942 { get; set; }
#endif
        /// <summary>The PersonMellomnavnTredjeTilknyttetGardNavnDatadef34941 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetGardNavndatadef34941? PersonMellomnavnTredjeTilknyttetGardNavnDatadef34941 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetGardNavndatadef34941 PersonMellomnavnTredjeTilknyttetGardNavnDatadef34941 { get; set; }
#endif
        /// <summary>The PersonMellomnavnTredjeTilknyttetPersonsEtternavnDatadef34940 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetPersonsEtternavndatadef34940? PersonMellomnavnTredjeTilknyttetPersonsEtternavnDatadef34940 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetPersonsEtternavndatadef34940 PersonMellomnavnTredjeTilknyttetPersonsEtternavnDatadef34940 { get; set; }
#endif
        /// <summary>The PersonMellomnavnTredjeTilknyttetPersonsFodselsnummerDatadef34939 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetPersonsFodselsnummerdatadef34939? PersonMellomnavnTredjeTilknyttetPersonsFodselsnummerDatadef34939 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetPersonsFodselsnummerdatadef34939 PersonMellomnavnTredjeTilknyttetPersonsFodselsnummerDatadef34939 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.TilknytningMellomnavn3grp9354"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.TilknytningMellomnavn3grp9354 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.TilknytningMellomnavn3grp9354();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "gruppeid", n => { Gruppeid = n.GetDoubleValue(); } },
                { "PersonMellomnavnTredje-datadef-34936", n => { PersonMellomnavnTredjeDatadef34936 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjedatadef34936>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjedatadef34936.CreateFromDiscriminatorValue); } },
                { "PersonMellomnavnTredjeTilknytningBeskrivelse-datadef-34938", n => { PersonMellomnavnTredjeTilknytningBeskrivelseDatadef34938 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknytningBeskrivelsedatadef34938>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknytningBeskrivelsedatadef34938.CreateFromDiscriminatorValue); } },
                { "PersonMellomnavnTredjeTilknytningstype-datadef-34937", n => { PersonMellomnavnTredjeTilknytningstypeDatadef34937 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknytningstypedatadef34937>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknytningstypedatadef34937.CreateFromDiscriminatorValue); } },
                { "PersonMellomnavnTredjeTilknyttetGardBruksnummer-datadef-34944", n => { PersonMellomnavnTredjeTilknyttetGardBruksnummerDatadef34944 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetGardBruksnummerdatadef34944>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetGardBruksnummerdatadef34944.CreateFromDiscriminatorValue); } },
                { "PersonMellomnavnTredjeTilknyttetGardFestenummer-datadef-34945", n => { PersonMellomnavnTredjeTilknyttetGardFestenummerDatadef34945 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetGardFestenummerdatadef34945>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetGardFestenummerdatadef34945.CreateFromDiscriminatorValue); } },
                { "PersonMellomnavnTredjeTilknyttetGardGardsnummer-datadef-34943", n => { PersonMellomnavnTredjeTilknyttetGardGardsnummerDatadef34943 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetGardGardsnummerdatadef34943>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetGardGardsnummerdatadef34943.CreateFromDiscriminatorValue); } },
                { "PersonMellomnavnTredjeTilknyttetGardKommunenummer-datadef-34942", n => { PersonMellomnavnTredjeTilknyttetGardKommunenummerDatadef34942 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetGardKommunenummerdatadef34942>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetGardKommunenummerdatadef34942.CreateFromDiscriminatorValue); } },
                { "PersonMellomnavnTredjeTilknyttetGardNavn-datadef-34941", n => { PersonMellomnavnTredjeTilknyttetGardNavnDatadef34941 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetGardNavndatadef34941>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetGardNavndatadef34941.CreateFromDiscriminatorValue); } },
                { "PersonMellomnavnTredjeTilknyttetPersonsEtternavn-datadef-34940", n => { PersonMellomnavnTredjeTilknyttetPersonsEtternavnDatadef34940 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetPersonsEtternavndatadef34940>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetPersonsEtternavndatadef34940.CreateFromDiscriminatorValue); } },
                { "PersonMellomnavnTredjeTilknyttetPersonsFodselsnummer-datadef-34939", n => { PersonMellomnavnTredjeTilknyttetPersonsFodselsnummerDatadef34939 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetPersonsFodselsnummerdatadef34939>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetPersonsFodselsnummerdatadef34939.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("gruppeid", Gruppeid);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjedatadef34936>("PersonMellomnavnTredje-datadef-34936", PersonMellomnavnTredjeDatadef34936);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknytningBeskrivelsedatadef34938>("PersonMellomnavnTredjeTilknytningBeskrivelse-datadef-34938", PersonMellomnavnTredjeTilknytningBeskrivelseDatadef34938);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknytningstypedatadef34937>("PersonMellomnavnTredjeTilknytningstype-datadef-34937", PersonMellomnavnTredjeTilknytningstypeDatadef34937);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetGardBruksnummerdatadef34944>("PersonMellomnavnTredjeTilknyttetGardBruksnummer-datadef-34944", PersonMellomnavnTredjeTilknyttetGardBruksnummerDatadef34944);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetGardFestenummerdatadef34945>("PersonMellomnavnTredjeTilknyttetGardFestenummer-datadef-34945", PersonMellomnavnTredjeTilknyttetGardFestenummerDatadef34945);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetGardGardsnummerdatadef34943>("PersonMellomnavnTredjeTilknyttetGardGardsnummer-datadef-34943", PersonMellomnavnTredjeTilknyttetGardGardsnummerDatadef34943);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetGardKommunenummerdatadef34942>("PersonMellomnavnTredjeTilknyttetGardKommunenummer-datadef-34942", PersonMellomnavnTredjeTilknyttetGardKommunenummerDatadef34942);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetGardNavndatadef34941>("PersonMellomnavnTredjeTilknyttetGardNavn-datadef-34941", PersonMellomnavnTredjeTilknyttetGardNavnDatadef34941);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetPersonsEtternavndatadef34940>("PersonMellomnavnTredjeTilknyttetPersonsEtternavn-datadef-34940", PersonMellomnavnTredjeTilknyttetPersonsEtternavnDatadef34940);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnTredjeTilknyttetPersonsFodselsnummerdatadef34939>("PersonMellomnavnTredjeTilknyttetPersonsFodselsnummer-datadef-34939", PersonMellomnavnTredjeTilknyttetPersonsFodselsnummerDatadef34939);
        }
    }
}
#pragma warning restore CS0618
