// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TilknytningEtternavn2grp9351 : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The gruppeid property</summary>
        public double? Gruppeid { get; set; }
        /// <summary>The PersonEtternavnAndreDatadef34906 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndredatadef34906? PersonEtternavnAndreDatadef34906 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndredatadef34906 PersonEtternavnAndreDatadef34906 { get; set; }
#endif
        /// <summary>The PersonEtternavnAndreTilknytningBeskrivelseDatadef34908 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknytningBeskrivelsedatadef34908? PersonEtternavnAndreTilknytningBeskrivelseDatadef34908 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknytningBeskrivelsedatadef34908 PersonEtternavnAndreTilknytningBeskrivelseDatadef34908 { get; set; }
#endif
        /// <summary>The PersonEtternavnAndreTilknytningstypeDatadef34907 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknytningstypedatadef34907? PersonEtternavnAndreTilknytningstypeDatadef34907 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknytningstypedatadef34907 PersonEtternavnAndreTilknytningstypeDatadef34907 { get; set; }
#endif
        /// <summary>The PersonEtternavnAndreTilknyttetGardBruksnummerDatadef34914 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetGardBruksnummerdatadef34914? PersonEtternavnAndreTilknyttetGardBruksnummerDatadef34914 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetGardBruksnummerdatadef34914 PersonEtternavnAndreTilknyttetGardBruksnummerDatadef34914 { get; set; }
#endif
        /// <summary>The PersonEtternavnAndreTilknyttetGardFesteavgiftDatadef34915 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetGardFesteavgiftdatadef34915? PersonEtternavnAndreTilknyttetGardFesteavgiftDatadef34915 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetGardFesteavgiftdatadef34915 PersonEtternavnAndreTilknyttetGardFesteavgiftDatadef34915 { get; set; }
#endif
        /// <summary>The PersonEtternavnAndreTilknyttetGardGardsnummerDatadef34913 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetGardGardsnummerdatadef34913? PersonEtternavnAndreTilknyttetGardGardsnummerDatadef34913 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetGardGardsnummerdatadef34913 PersonEtternavnAndreTilknyttetGardGardsnummerDatadef34913 { get; set; }
#endif
        /// <summary>The PersonEtternavnAndreTilknyttetGardKommunenummerDatadef34912 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetGardKommunenummerdatadef34912? PersonEtternavnAndreTilknyttetGardKommunenummerDatadef34912 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetGardKommunenummerdatadef34912 PersonEtternavnAndreTilknyttetGardKommunenummerDatadef34912 { get; set; }
#endif
        /// <summary>The PersonEtternavnAndreTilknyttetGardNavnDatadef34911 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetGardNavndatadef34911? PersonEtternavnAndreTilknyttetGardNavnDatadef34911 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetGardNavndatadef34911 PersonEtternavnAndreTilknyttetGardNavnDatadef34911 { get; set; }
#endif
        /// <summary>The PersonEtternavnAndreTilknyttetPersonsEtternavnDatadef34910 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetPersonsEtternavndatadef34910? PersonEtternavnAndreTilknyttetPersonsEtternavnDatadef34910 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetPersonsEtternavndatadef34910 PersonEtternavnAndreTilknyttetPersonsEtternavnDatadef34910 { get; set; }
#endif
        /// <summary>The PersonEtternavnAndreTilknyttetPersonsFodselsnummerDatadef34909 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetPersonsFodselsnummerdatadef34909? PersonEtternavnAndreTilknyttetPersonsFodselsnummerDatadef34909 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetPersonsFodselsnummerdatadef34909 PersonEtternavnAndreTilknyttetPersonsFodselsnummerDatadef34909 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.TilknytningEtternavn2grp9351"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.TilknytningEtternavn2grp9351 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.TilknytningEtternavn2grp9351();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "gruppeid", n => { Gruppeid = n.GetDoubleValue(); } },
                { "PersonEtternavnAndre-datadef-34906", n => { PersonEtternavnAndreDatadef34906 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndredatadef34906>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndredatadef34906.CreateFromDiscriminatorValue); } },
                { "PersonEtternavnAndreTilknytningBeskrivelse-datadef-34908", n => { PersonEtternavnAndreTilknytningBeskrivelseDatadef34908 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknytningBeskrivelsedatadef34908>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknytningBeskrivelsedatadef34908.CreateFromDiscriminatorValue); } },
                { "PersonEtternavnAndreTilknytningstype-datadef-34907", n => { PersonEtternavnAndreTilknytningstypeDatadef34907 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknytningstypedatadef34907>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknytningstypedatadef34907.CreateFromDiscriminatorValue); } },
                { "PersonEtternavnAndreTilknyttetGardBruksnummer-datadef-34914", n => { PersonEtternavnAndreTilknyttetGardBruksnummerDatadef34914 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetGardBruksnummerdatadef34914>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetGardBruksnummerdatadef34914.CreateFromDiscriminatorValue); } },
                { "PersonEtternavnAndreTilknyttetGardFesteavgift-datadef-34915", n => { PersonEtternavnAndreTilknyttetGardFesteavgiftDatadef34915 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetGardFesteavgiftdatadef34915>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetGardFesteavgiftdatadef34915.CreateFromDiscriminatorValue); } },
                { "PersonEtternavnAndreTilknyttetGardGardsnummer-datadef-34913", n => { PersonEtternavnAndreTilknyttetGardGardsnummerDatadef34913 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetGardGardsnummerdatadef34913>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetGardGardsnummerdatadef34913.CreateFromDiscriminatorValue); } },
                { "PersonEtternavnAndreTilknyttetGardKommunenummer-datadef-34912", n => { PersonEtternavnAndreTilknyttetGardKommunenummerDatadef34912 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetGardKommunenummerdatadef34912>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetGardKommunenummerdatadef34912.CreateFromDiscriminatorValue); } },
                { "PersonEtternavnAndreTilknyttetGardNavn-datadef-34911", n => { PersonEtternavnAndreTilknyttetGardNavnDatadef34911 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetGardNavndatadef34911>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetGardNavndatadef34911.CreateFromDiscriminatorValue); } },
                { "PersonEtternavnAndreTilknyttetPersonsEtternavn-datadef-34910", n => { PersonEtternavnAndreTilknyttetPersonsEtternavnDatadef34910 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetPersonsEtternavndatadef34910>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetPersonsEtternavndatadef34910.CreateFromDiscriminatorValue); } },
                { "PersonEtternavnAndreTilknyttetPersonsFodselsnummer-datadef-34909", n => { PersonEtternavnAndreTilknyttetPersonsFodselsnummerDatadef34909 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetPersonsFodselsnummerdatadef34909>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetPersonsFodselsnummerdatadef34909.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("gruppeid", Gruppeid);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndredatadef34906>("PersonEtternavnAndre-datadef-34906", PersonEtternavnAndreDatadef34906);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknytningBeskrivelsedatadef34908>("PersonEtternavnAndreTilknytningBeskrivelse-datadef-34908", PersonEtternavnAndreTilknytningBeskrivelseDatadef34908);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknytningstypedatadef34907>("PersonEtternavnAndreTilknytningstype-datadef-34907", PersonEtternavnAndreTilknytningstypeDatadef34907);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetGardBruksnummerdatadef34914>("PersonEtternavnAndreTilknyttetGardBruksnummer-datadef-34914", PersonEtternavnAndreTilknyttetGardBruksnummerDatadef34914);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetGardFesteavgiftdatadef34915>("PersonEtternavnAndreTilknyttetGardFesteavgift-datadef-34915", PersonEtternavnAndreTilknyttetGardFesteavgiftDatadef34915);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetGardGardsnummerdatadef34913>("PersonEtternavnAndreTilknyttetGardGardsnummer-datadef-34913", PersonEtternavnAndreTilknyttetGardGardsnummerDatadef34913);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetGardKommunenummerdatadef34912>("PersonEtternavnAndreTilknyttetGardKommunenummer-datadef-34912", PersonEtternavnAndreTilknyttetGardKommunenummerDatadef34912);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetGardNavndatadef34911>("PersonEtternavnAndreTilknyttetGardNavn-datadef-34911", PersonEtternavnAndreTilknyttetGardNavnDatadef34911);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetPersonsEtternavndatadef34910>("PersonEtternavnAndreTilknyttetPersonsEtternavn-datadef-34910", PersonEtternavnAndreTilknyttetPersonsEtternavnDatadef34910);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnAndreTilknyttetPersonsFodselsnummerdatadef34909>("PersonEtternavnAndreTilknyttetPersonsFodselsnummer-datadef-34909", PersonEtternavnAndreTilknyttetPersonsFodselsnummerDatadef34909);
        }
    }
}
#pragma warning restore CS0618
