// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TilknytningMellomnavn1grp9352 : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The gruppeid property</summary>
        public double? Gruppeid { get; set; }
        /// <summary>The PersonMellomnavnForsteDatadef34916 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForstedatadef34916? PersonMellomnavnForsteDatadef34916 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForstedatadef34916 PersonMellomnavnForsteDatadef34916 { get; set; }
#endif
        /// <summary>The PersonMellomnavnForsteTilknytningBeskrivelseDatadef34918 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknytningBeskrivelsedatadef34918? PersonMellomnavnForsteTilknytningBeskrivelseDatadef34918 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknytningBeskrivelsedatadef34918 PersonMellomnavnForsteTilknytningBeskrivelseDatadef34918 { get; set; }
#endif
        /// <summary>The PersonMellomnavnForsteTilknytningstypeDatadef34917 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknytningstypedatadef34917? PersonMellomnavnForsteTilknytningstypeDatadef34917 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknytningstypedatadef34917 PersonMellomnavnForsteTilknytningstypeDatadef34917 { get; set; }
#endif
        /// <summary>The PersonMellomnavnForsteTilknyttetGardBruksnummerDatadef34924 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetGardBruksnummerdatadef34924? PersonMellomnavnForsteTilknyttetGardBruksnummerDatadef34924 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetGardBruksnummerdatadef34924 PersonMellomnavnForsteTilknyttetGardBruksnummerDatadef34924 { get; set; }
#endif
        /// <summary>The PersonMellomnavnForsteTilknyttetGardFestenummerDatadef34925 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetGardFestenummerdatadef34925? PersonMellomnavnForsteTilknyttetGardFestenummerDatadef34925 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetGardFestenummerdatadef34925 PersonMellomnavnForsteTilknyttetGardFestenummerDatadef34925 { get; set; }
#endif
        /// <summary>The PersonMellomnavnForsteTilknyttetGardGardsnummerDatadef34923 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetGardGardsnummerdatadef34923? PersonMellomnavnForsteTilknyttetGardGardsnummerDatadef34923 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetGardGardsnummerdatadef34923 PersonMellomnavnForsteTilknyttetGardGardsnummerDatadef34923 { get; set; }
#endif
        /// <summary>The PersonMellomnavnForsteTilknyttetGardKommunenummerDatadef34922 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetGardKommunenummerdatadef34922? PersonMellomnavnForsteTilknyttetGardKommunenummerDatadef34922 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetGardKommunenummerdatadef34922 PersonMellomnavnForsteTilknyttetGardKommunenummerDatadef34922 { get; set; }
#endif
        /// <summary>The PersonMellomnavnForsteTilknyttetGardNavnDatadef34921 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetGardNavndatadef34921? PersonMellomnavnForsteTilknyttetGardNavnDatadef34921 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetGardNavndatadef34921 PersonMellomnavnForsteTilknyttetGardNavnDatadef34921 { get; set; }
#endif
        /// <summary>The PersonMellomnavnForsteTilknyttetPersonsEtternavnDatadef34920 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetPersonsEtternavndatadef34920? PersonMellomnavnForsteTilknyttetPersonsEtternavnDatadef34920 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetPersonsEtternavndatadef34920 PersonMellomnavnForsteTilknyttetPersonsEtternavnDatadef34920 { get; set; }
#endif
        /// <summary>The PersonMellomnavnForsteTilknyttetPersonsFodselsnummerDatadef34919 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetPersonsFodselsnummerdatadef34919? PersonMellomnavnForsteTilknyttetPersonsFodselsnummerDatadef34919 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetPersonsFodselsnummerdatadef34919 PersonMellomnavnForsteTilknyttetPersonsFodselsnummerDatadef34919 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.TilknytningMellomnavn1grp9352"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.TilknytningMellomnavn1grp9352 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.TilknytningMellomnavn1grp9352();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "gruppeid", n => { Gruppeid = n.GetDoubleValue(); } },
                { "PersonMellomnavnForste-datadef-34916", n => { PersonMellomnavnForsteDatadef34916 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForstedatadef34916>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForstedatadef34916.CreateFromDiscriminatorValue); } },
                { "PersonMellomnavnForsteTilknytningBeskrivelse-datadef-34918", n => { PersonMellomnavnForsteTilknytningBeskrivelseDatadef34918 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknytningBeskrivelsedatadef34918>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknytningBeskrivelsedatadef34918.CreateFromDiscriminatorValue); } },
                { "PersonMellomnavnForsteTilknytningstype-datadef-34917", n => { PersonMellomnavnForsteTilknytningstypeDatadef34917 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknytningstypedatadef34917>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknytningstypedatadef34917.CreateFromDiscriminatorValue); } },
                { "PersonMellomnavnForsteTilknyttetGardBruksnummer-datadef-34924", n => { PersonMellomnavnForsteTilknyttetGardBruksnummerDatadef34924 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetGardBruksnummerdatadef34924>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetGardBruksnummerdatadef34924.CreateFromDiscriminatorValue); } },
                { "PersonMellomnavnForsteTilknyttetGardFestenummer-datadef-34925", n => { PersonMellomnavnForsteTilknyttetGardFestenummerDatadef34925 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetGardFestenummerdatadef34925>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetGardFestenummerdatadef34925.CreateFromDiscriminatorValue); } },
                { "PersonMellomnavnForsteTilknyttetGardGardsnummer-datadef-34923", n => { PersonMellomnavnForsteTilknyttetGardGardsnummerDatadef34923 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetGardGardsnummerdatadef34923>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetGardGardsnummerdatadef34923.CreateFromDiscriminatorValue); } },
                { "PersonMellomnavnForsteTilknyttetGardKommunenummer-datadef-34922", n => { PersonMellomnavnForsteTilknyttetGardKommunenummerDatadef34922 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetGardKommunenummerdatadef34922>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetGardKommunenummerdatadef34922.CreateFromDiscriminatorValue); } },
                { "PersonMellomnavnForsteTilknyttetGardNavn-datadef-34921", n => { PersonMellomnavnForsteTilknyttetGardNavnDatadef34921 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetGardNavndatadef34921>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetGardNavndatadef34921.CreateFromDiscriminatorValue); } },
                { "PersonMellomnavnForsteTilknyttetPersonsEtternavn-datadef-34920", n => { PersonMellomnavnForsteTilknyttetPersonsEtternavnDatadef34920 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetPersonsEtternavndatadef34920>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetPersonsEtternavndatadef34920.CreateFromDiscriminatorValue); } },
                { "PersonMellomnavnForsteTilknyttetPersonsFodselsnummer-datadef-34919", n => { PersonMellomnavnForsteTilknyttetPersonsFodselsnummerDatadef34919 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetPersonsFodselsnummerdatadef34919>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetPersonsFodselsnummerdatadef34919.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("gruppeid", Gruppeid);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForstedatadef34916>("PersonMellomnavnForste-datadef-34916", PersonMellomnavnForsteDatadef34916);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknytningBeskrivelsedatadef34918>("PersonMellomnavnForsteTilknytningBeskrivelse-datadef-34918", PersonMellomnavnForsteTilknytningBeskrivelseDatadef34918);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknytningstypedatadef34917>("PersonMellomnavnForsteTilknytningstype-datadef-34917", PersonMellomnavnForsteTilknytningstypeDatadef34917);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetGardBruksnummerdatadef34924>("PersonMellomnavnForsteTilknyttetGardBruksnummer-datadef-34924", PersonMellomnavnForsteTilknyttetGardBruksnummerDatadef34924);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetGardFestenummerdatadef34925>("PersonMellomnavnForsteTilknyttetGardFestenummer-datadef-34925", PersonMellomnavnForsteTilknyttetGardFestenummerDatadef34925);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetGardGardsnummerdatadef34923>("PersonMellomnavnForsteTilknyttetGardGardsnummer-datadef-34923", PersonMellomnavnForsteTilknyttetGardGardsnummerDatadef34923);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetGardKommunenummerdatadef34922>("PersonMellomnavnForsteTilknyttetGardKommunenummer-datadef-34922", PersonMellomnavnForsteTilknyttetGardKommunenummerDatadef34922);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetGardNavndatadef34921>("PersonMellomnavnForsteTilknyttetGardNavn-datadef-34921", PersonMellomnavnForsteTilknyttetGardNavnDatadef34921);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetPersonsEtternavndatadef34920>("PersonMellomnavnForsteTilknyttetPersonsEtternavn-datadef-34920", PersonMellomnavnForsteTilknyttetPersonsEtternavnDatadef34920);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonMellomnavnForsteTilknyttetPersonsFodselsnummerdatadef34919>("PersonMellomnavnForsteTilknyttetPersonsFodselsnummer-datadef-34919", PersonMellomnavnForsteTilknyttetPersonsFodselsnummerDatadef34919);
        }
    }
}
#pragma warning restore CS0618
