// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TilknytningEtternavn1grp9350 : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The gruppeid property</summary>
        public double? Gruppeid { get; set; }
        /// <summary>The PersonEtternavnForsteDatadef34896 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForstedatadef34896? PersonEtternavnForsteDatadef34896 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForstedatadef34896 PersonEtternavnForsteDatadef34896 { get; set; }
#endif
        /// <summary>The PersonEtternavnForsteTilknytningBeskrivelseDatadef34898 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknytningBeskrivelsedatadef34898? PersonEtternavnForsteTilknytningBeskrivelseDatadef34898 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknytningBeskrivelsedatadef34898 PersonEtternavnForsteTilknytningBeskrivelseDatadef34898 { get; set; }
#endif
        /// <summary>The PersonEtternavnForsteTilknytningstypeDatadef34897 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknytningstypedatadef34897? PersonEtternavnForsteTilknytningstypeDatadef34897 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknytningstypedatadef34897 PersonEtternavnForsteTilknytningstypeDatadef34897 { get; set; }
#endif
        /// <summary>The PersonEtternavnForsteTilknyttetGardBruksnummerDatadef34904 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetGardBruksnummerdatadef34904? PersonEtternavnForsteTilknyttetGardBruksnummerDatadef34904 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetGardBruksnummerdatadef34904 PersonEtternavnForsteTilknyttetGardBruksnummerDatadef34904 { get; set; }
#endif
        /// <summary>The PersonEtternavnForsteTilknyttetGardFesteavgiftDatadef34905 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetGardFesteavgiftdatadef34905? PersonEtternavnForsteTilknyttetGardFesteavgiftDatadef34905 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetGardFesteavgiftdatadef34905 PersonEtternavnForsteTilknyttetGardFesteavgiftDatadef34905 { get; set; }
#endif
        /// <summary>The PersonEtternavnForsteTilknyttetGardGardsnummerDatadef34903 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetGardGardsnummerdatadef34903? PersonEtternavnForsteTilknyttetGardGardsnummerDatadef34903 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetGardGardsnummerdatadef34903 PersonEtternavnForsteTilknyttetGardGardsnummerDatadef34903 { get; set; }
#endif
        /// <summary>The PersonEtternavnForsteTilknyttetGardKommunenummerDatadef34902 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetGardKommunenummerdatadef34902? PersonEtternavnForsteTilknyttetGardKommunenummerDatadef34902 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetGardKommunenummerdatadef34902 PersonEtternavnForsteTilknyttetGardKommunenummerDatadef34902 { get; set; }
#endif
        /// <summary>The PersonEtternavnForsteTilknyttetGardNavnDatadef34901 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetGardNavndatadef34901? PersonEtternavnForsteTilknyttetGardNavnDatadef34901 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetGardNavndatadef34901 PersonEtternavnForsteTilknyttetGardNavnDatadef34901 { get; set; }
#endif
        /// <summary>The PersonEtternavnForsteTilknyttetPersonsEtternavnDatadef34900 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetPersonsEtternavndatadef34900? PersonEtternavnForsteTilknyttetPersonsEtternavnDatadef34900 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetPersonsEtternavndatadef34900 PersonEtternavnForsteTilknyttetPersonsEtternavnDatadef34900 { get; set; }
#endif
        /// <summary>The PersonEtternavnForsteTilknyttetPersonsFodselsnummerDatadef34899 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetPersonsFodselsnummerdatadef34899? PersonEtternavnForsteTilknyttetPersonsFodselsnummerDatadef34899 { get; set; }
#nullable restore
#else
        public global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetPersonsFodselsnummerdatadef34899 PersonEtternavnForsteTilknyttetPersonsFodselsnummerDatadef34899 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.TilknytningEtternavn1grp9350"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.TilknytningEtternavn1grp9350 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.TilknytningEtternavn1grp9350();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "gruppeid", n => { Gruppeid = n.GetDoubleValue(); } },
                { "PersonEtternavnForste-datadef-34896", n => { PersonEtternavnForsteDatadef34896 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForstedatadef34896>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForstedatadef34896.CreateFromDiscriminatorValue); } },
                { "PersonEtternavnForsteTilknytningBeskrivelse-datadef-34898", n => { PersonEtternavnForsteTilknytningBeskrivelseDatadef34898 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknytningBeskrivelsedatadef34898>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknytningBeskrivelsedatadef34898.CreateFromDiscriminatorValue); } },
                { "PersonEtternavnForsteTilknytningstype-datadef-34897", n => { PersonEtternavnForsteTilknytningstypeDatadef34897 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknytningstypedatadef34897>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknytningstypedatadef34897.CreateFromDiscriminatorValue); } },
                { "PersonEtternavnForsteTilknyttetGardBruksnummer-datadef-34904", n => { PersonEtternavnForsteTilknyttetGardBruksnummerDatadef34904 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetGardBruksnummerdatadef34904>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetGardBruksnummerdatadef34904.CreateFromDiscriminatorValue); } },
                { "PersonEtternavnForsteTilknyttetGardFesteavgift-datadef-34905", n => { PersonEtternavnForsteTilknyttetGardFesteavgiftDatadef34905 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetGardFesteavgiftdatadef34905>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetGardFesteavgiftdatadef34905.CreateFromDiscriminatorValue); } },
                { "PersonEtternavnForsteTilknyttetGardGardsnummer-datadef-34903", n => { PersonEtternavnForsteTilknyttetGardGardsnummerDatadef34903 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetGardGardsnummerdatadef34903>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetGardGardsnummerdatadef34903.CreateFromDiscriminatorValue); } },
                { "PersonEtternavnForsteTilknyttetGardKommunenummer-datadef-34902", n => { PersonEtternavnForsteTilknyttetGardKommunenummerDatadef34902 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetGardKommunenummerdatadef34902>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetGardKommunenummerdatadef34902.CreateFromDiscriminatorValue); } },
                { "PersonEtternavnForsteTilknyttetGardNavn-datadef-34901", n => { PersonEtternavnForsteTilknyttetGardNavnDatadef34901 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetGardNavndatadef34901>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetGardNavndatadef34901.CreateFromDiscriminatorValue); } },
                { "PersonEtternavnForsteTilknyttetPersonsEtternavn-datadef-34900", n => { PersonEtternavnForsteTilknyttetPersonsEtternavnDatadef34900 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetPersonsEtternavndatadef34900>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetPersonsEtternavndatadef34900.CreateFromDiscriminatorValue); } },
                { "PersonEtternavnForsteTilknyttetPersonsFodselsnummer-datadef-34899", n => { PersonEtternavnForsteTilknyttetPersonsFodselsnummerDatadef34899 = n.GetObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetPersonsFodselsnummerdatadef34899>(global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetPersonsFodselsnummerdatadef34899.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("gruppeid", Gruppeid);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForstedatadef34896>("PersonEtternavnForste-datadef-34896", PersonEtternavnForsteDatadef34896);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknytningBeskrivelsedatadef34898>("PersonEtternavnForsteTilknytningBeskrivelse-datadef-34898", PersonEtternavnForsteTilknytningBeskrivelseDatadef34898);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknytningstypedatadef34897>("PersonEtternavnForsteTilknytningstype-datadef-34897", PersonEtternavnForsteTilknytningstypeDatadef34897);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetGardBruksnummerdatadef34904>("PersonEtternavnForsteTilknyttetGardBruksnummer-datadef-34904", PersonEtternavnForsteTilknyttetGardBruksnummerDatadef34904);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetGardFesteavgiftdatadef34905>("PersonEtternavnForsteTilknyttetGardFesteavgift-datadef-34905", PersonEtternavnForsteTilknyttetGardFesteavgiftDatadef34905);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetGardGardsnummerdatadef34903>("PersonEtternavnForsteTilknyttetGardGardsnummer-datadef-34903", PersonEtternavnForsteTilknyttetGardGardsnummerDatadef34903);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetGardKommunenummerdatadef34902>("PersonEtternavnForsteTilknyttetGardKommunenummer-datadef-34902", PersonEtternavnForsteTilknyttetGardKommunenummerDatadef34902);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetGardNavndatadef34901>("PersonEtternavnForsteTilknyttetGardNavn-datadef-34901", PersonEtternavnForsteTilknyttetGardNavnDatadef34901);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetPersonsEtternavndatadef34900>("PersonEtternavnForsteTilknyttetPersonsEtternavn-datadef-34900", PersonEtternavnForsteTilknyttetPersonsEtternavnDatadef34900);
            writer.WriteObjectValue<global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.PersonEtternavnForsteTilknyttetPersonsFodselsnummerdatadef34899>("PersonEtternavnForsteTilknyttetPersonsFodselsnummer-datadef-34899", PersonEtternavnForsteTilknyttetPersonsFodselsnummerDatadef34899);
        }
    }
}
#pragma warning restore CS0618
