// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ValidationIssueWithSource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The code property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Code { get; set; }
#nullable restore
#else
        public string Code { get; set; }
#endif
        /// <summary>The customTextKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomTextKey { get; set; }
#nullable restore
#else
        public string CustomTextKey { get; set; }
#endif
        /// <summary>The customTextParams property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CustomTextParams { get; set; }
#nullable restore
#else
        public List<string> CustomTextParams { get; set; }
#endif
        /// <summary>The dataElementId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DataElementId { get; set; }
#nullable restore
#else
        public string DataElementId { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The field property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Field { get; set; }
#nullable restore
#else
        public string Field { get; set; }
#endif
        /// <summary>The noIncrementalUpdates property</summary>
        public bool? NoIncrementalUpdates { get; set; }
        /// <summary>The severity property</summary>
        public int? Severity { get; set; }
        /// <summary>The source property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Source { get; set; }
#nullable restore
#else
        public string Source { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ValidationIssueWithSource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ValidationIssueWithSource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Altinn.App.Integration.FrontendTests.GeneratedClient.KiotaGenerated.Models.ValidationIssueWithSource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "code", n => { Code = n.GetStringValue(); } },
                { "customTextKey", n => { CustomTextKey = n.GetStringValue(); } },
                { "customTextParams", n => { CustomTextParams = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "dataElementId", n => { DataElementId = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "field", n => { Field = n.GetStringValue(); } },
                { "noIncrementalUpdates", n => { NoIncrementalUpdates = n.GetBoolValue(); } },
                { "severity", n => { Severity = n.GetIntValue(); } },
                { "source", n => { Source = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("code", Code);
            writer.WriteStringValue("customTextKey", CustomTextKey);
            writer.WriteCollectionOfPrimitiveValues<string>("customTextParams", CustomTextParams);
            writer.WriteStringValue("dataElementId", DataElementId);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("field", Field);
            writer.WriteBoolValue("noIncrementalUpdates", NoIncrementalUpdates);
            writer.WriteIntValue("severity", Severity);
            writer.WriteStringValue("source", Source);
        }
    }
}
#pragma warning restore CS0618
