# permissions for end users to edit maskinportenclients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: maskinportenclient-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: altinn-maskinporten-operator
    app.kubernetes.io/part-of: altinn-maskinporten-operator
    app.kubernetes.io/managed-by: kustomize
  name: maskinportenclient-editor-role
rules:
- apiGroups:
  - client.altinn.operator
  resources:
  - maskinportenclients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - client.altinn.operator
  resources:
  - maskinportenclients/status
  verbs:
  - get
