name: Add new issues to Team Apps project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to Team Altinn Studio project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd # main
        with:
          project-url: https://github.com/orgs/Altinn/projects/164
          github-token: ${{ secrets.ASSIGN_PROJECT_TOKEN }}
