name: Add new issues to Team Apps project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to Team Altinn Studio project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@cbad230d1debaae844a2c6f675327ab6c537e0f1 # main
        with:
          project-url: https://github.com/orgs/Altinn/projects/164
          github-token: ${{ secrets.ASSIGN_PROJECT_TOKEN }}
