name: Pack and publish

on:
  release:
    types:
      - published

jobs:
  release-nugets:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    environment: |-
      ${{
         contains(github.event.release.tag_name, 'preview') && 'test'
      || contains(github.event.release.tag_name, 'rc')      && 'staging'
      ||                                                       'prod'
      }}
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - name: Validate tag
        env:
          REGEX: "${{ github.event.release.prerelease && '^v(\\d+)\\.(\\d+)\\.(\\d+)-(preview|rc)\\.\\d+$' ||
                                                         '^v(\\d+)\\.(\\d+)\\.(\\d+)$' }}"
        run: |
          echo "Validating that the tag is in the correct format"
          echo "${{ github.event.release.tag_name }}" | grep -P $REGEX

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Install dotnet8
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
        with:
          dotnet-version: |
            8.0.x

      - name: Extract release notes
        id: extract-notes
        run: |
          echo "Release notes look best on GitHub: ${{ github.event.release.html_url }}" > RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "${{ github.event.release.body }}" >> RELEASE_NOTES.md
          cat RELEASE_NOTES.md

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore -p:Deterministic=true -p:BuildNumber=${{ github.run_number }}

      - name: Build
        run: dotnet build -c Release --no-restore -p:Deterministic=true -p:BuildNumber=${{ github.run_number }}

      - name: Pack
        run: dotnet pack -c Release --no-restore --no-build -p:Deterministic=true -p:BuildNumber=${{ github.run_number }}

      - name: Publish
        run: |
          dotnet nuget push src/**/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
